### PR TITLE
Add support for building images based on scratch

### PR DESCRIPTION
**Pull request by JosephSalisbury**

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
@giantswarm/team-obolus RFR

**Comment by xh3b4sd** [comment]
I don't understand the problem this PR tries to solve.

**Comment by JosephSalisbury** [comment]
While attempting to release https://github.com/giantswarm/prometheus-kemp-exporter - which uses a Dockerfile coming from `scratch`, I get:
```
Searching for the base image in your Dockerfile
Pulling version 'latest' of your base image
docker pull scratch:latest
Looks like something went wrong during the release process:


    The following command failed:

        docker pull scratch:latest

    Output of stderr was:

        Error response from daemon: 'scratch' is a reserved name
```

The name is reserved as `scratch` is the empty Docker image. This PR stops us attempting to pull this non-existent image.

**Comment by hectorj2f** [comment]
@JosephSalisbury This doesn't make sense, builder should complain as it does. In fact, you should change the image to `tianon/true` which is the replacement of scratch. Anyway, scratch is an empty image.

**Comment by xh3b4sd** [comment]
+1 on what hector said. Having such special exceptions because of weird concepts in third party software does not feel right.

**Comment by teemow** [comment]
LGTM

@hectorj2f @xh3b4sd to me this is a valid fix. we should absolutely fix this.

**Comment by hectorj2f** [comment]
@teemow What to skip an error if the docker image is `scratch`... Don't understand. The image is not valid anymore so we should get an error... to change it in our Dockerfiles

**Comment by hectorj2f** [comment]
@JosephSalisbury LGTM

**Pull request merged**
